# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 709a80c42d6d8f0315c629ad76fc6ebc07129d2482509d1c31ba47032856905a9e59a4b6e97eb639afb0be59361a59017239a0d7352b666a659cfeb13cb55c85

test:
  secret_key_base: 1ded24ffbf3d105ba0be8d7ed4532c616ca3fbc30c33221250251ca78fd89474057639b802f73e920f99b2ae45e6e641af9ceaf2f249c9bf3255f58f968ba2dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
